import { createBrowserRouter } from "react-router";
import { RootLayout } from "./components/RootLayout";
import { HomePage } from "./components/HomePage";

export const router = createBrowserRouter([
  {
    path: "/",
    Component: RootLayout,
    children: [
      { index: true, Component: HomePage },
      { path: "catalogo", lazy: () => import("./components/CatalogPage").then(m => ({ Component: m.CatalogPage })) },
      { path: "entrar", lazy: () => import("./components/UserAuthPage").then(m => ({ Component: m.UserAuthPage })) },
      { path: "minha-conta", lazy: () => import("./components/UserAccountPage").then(m => ({ Component: m.UserAccountPage })) },
      { path: "pagamento/:projectId", lazy: () => import("./components/PaymentPage").then(m => ({ Component: m.PaymentPage })) },
      { path: "parcelas/:projectId", lazy: () => import("./components/InstallmentCheckoutPage").then(m => ({ Component: m.InstallmentCheckoutPage })) },
      { path: "contrato/:projectId", lazy: () => import("./components/ContractViewPage").then(m => ({ Component: m.ContractViewPage })) },
      { path: "nova-solicitacao", lazy: () => import("./components/NewRequestPage").then(m => ({ Component: m.NewRequestPage })) },
      { path: "livros/:slug", lazy: () => import("./components/BookDetailPage").then(m => ({ Component: m.BookDetailPage })) },
      { path: "privacidade", lazy: () => import("./components/PrivacyPage").then(m => ({ Component: m.PrivacyPage })) },
      { path: "meus-dados", lazy: () => import("./components/MeusDadosPage").then(m => ({ Component: m.MeusDadosPage })) },
      { path: "termos", lazy: () => import("./components/TermsPage").then(m => ({ Component: m.TermsPage })) },
      { path: "recuperar-senha", lazy: () => import("./components/PasswordResetPage").then(m => ({ Component: m.PasswordResetPage })) },
      {
        path: "admin",
        lazy: () => import("./components/admin/AdminLogin").then(m => ({ Component: m.AdminLogin })),
      },
      { path: "admin/*", lazy: () => import("./components/NotFoundPage").then(m => ({ Component: m.NotFoundPage })) },
      { path: "*", lazy: () => import("./components/NotFoundPage").then(m => ({ Component: m.NotFoundPage })) },
    ],
  },
  {
    path: "/admin",
    lazy: () => import("./components/admin/AdminLayout").then(m => ({ Component: m.AdminLayout })),
    children: [
      { path: "dashboard", lazy: () => import("./components/admin/AdminDashboard").then(m => ({ Component: m.AdminDashboard })) },
      { path: "mensagens", lazy: () => import("./components/admin/AdminMessages").then(m => ({ Component: m.AdminMessages })) },
      { path: "usuarios", lazy: () => import("./components/admin/AdminUsers").then(m => ({ Component: m.AdminUsers })) },
      { path: "livros", lazy: () => import("./components/admin/AdminBooks").then(m => ({ Component: m.AdminBooks })) },
      { path: "projetos", lazy: () => import("./components/admin/AdminProjects").then(m => ({ Component: m.AdminProjects })) },
      { path: "contratos", lazy: () => import("./components/admin/AdminContracts").then(m => ({ Component: m.AdminContracts })) },
      { path: "faq", lazy: () => import("./components/admin/AdminFaq").then(m => ({ Component: m.AdminFaq })) },
      { path: "newsletter", lazy: () => import("./components/admin/AdminNewsletter").then(m => ({ Component: m.AdminNewsletter })) },
      { path: "planos", lazy: () => import("./components/admin/AdminPlans").then(m => ({ Component: m.AdminPlans })) },
      { path: "video", lazy: () => import("./components/admin/AdminVideo").then(m => ({ Component: m.AdminVideo })) },
      { path: "autores", lazy: () => import("./components/admin/AdminAuthors").then(m => ({ Component: m.AdminAuthors })) },
      { path: "depoimentos", lazy: () => import("./components/admin/AdminTestimonials").then(m => ({ Component: m.AdminTestimonials })) },
      { path: "sobre", lazy: () => import("./components/admin/AdminAbout").then(m => ({ Component: m.AdminAbout })) },
      { path: "logo", lazy: () => import("./components/admin/AdminLogo").then(m => ({ Component: m.AdminLogo })) },
      { path: "pagamentos", lazy: () => import("./components/admin/AdminPaymentConfig").then(m => ({ Component: m.AdminPaymentConfig })) },
      { path: "contato", lazy: () => import("./components/admin/AdminContactInfo").then(m => ({ Component: m.AdminContactInfo })) },
      { path: "integracoes", lazy: () => import("./components/admin/AdminTracking").then(m => ({ Component: m.AdminTracking })) },
      { path: "email-config", lazy: () => import("./components/admin/AdminEmailConfig").then(m => ({ Component: m.AdminEmailConfig })) },
      { path: "email-marketing", lazy: () => import("./components/admin/AdminEmailMarketing").then(m => ({ Component: m.AdminEmailMarketing })) },
      { path: "compor-email", lazy: () => import("./components/admin/AdminComposeMail").then(m => ({ Component: m.AdminComposeMail })) },
      { path: "inbox", lazy: () => import("./components/admin/AdminInbox").then(m => ({ Component: m.AdminInbox })) },
      { path: "hero", lazy: () => import("./components/admin/AdminHero").then(m => ({ Component: m.AdminHero })) },
      { path: "sobre-texto", lazy: () => import("./components/admin/AdminAboutContent").then(m => ({ Component: m.AdminAboutContent })) },
      { path: "cta-banner", lazy: () => import("./components/admin/AdminCtaBanner").then(m => ({ Component: m.AdminCtaBanner })) },
      { path: "rodape", lazy: () => import("./components/admin/AdminFooter").then(m => ({ Component: m.AdminFooter })) },
    ],
  },
]);
